### ISSUE TITLE
Readme / Wiki

### ISSUE THREAD

**Issue by Aetherinox** [acheong08/rev-obsidian-sync#26]
I don't recall if closed issues give notifications. Been awhile since I've messed with issues/tickets.

Here's the doc: https://github.com/Aetherinox/obi-sync-docs/blob/main/README.md

I tried to keep it as simple as possible, but also cover all the bases. You can pick out parts if you want to shorten the readme, or if you want to create a few Wiki pages and copy/paste the contents. The images are uploaded to github, so you don't need to go shuffling them around.  I also confirmed with Github to make sure the images won't expire or poof / disappear, and they won't. As long as there's no Terms of Service violation; which there isn't.

It pretty much covers Sync and Publish, along with configuration. It went through it at a few different occasions today to re-read and check for grammar, shorten the words, etc. For the most part everything looks OK.

Also provided a revised template for people who want to use an `.env` file for variables instead of editing the `docker-compose.yml` which is located [here](https://github.com/Aetherinox/obi-sync-docs/blob/main/README.md#-docker-composeyml--env).

Hope it helps.

**Comment by acheong08** [comment]
Thank you so much! I'll organize this into the wiki.

**Comment by acheong08** [comment]
https://github.com/acheong08/obi-sync/wiki

Looks great!

**Comment by Aetherinox** [comment]
Looks good. May want to fix a few of the links though so they point to the right sections. I forgot the wiki section doesn't have the ability to request changes.

Looks like there's about 7 or so header links.

**Comment by acheong08** [comment]
Fixed (I think)

> I forgot the wiki section doesn't have the ability to request changes.

I'll mirror the wiki into the main repo

**Comment by Aetherinox** [comment]
Thanks. I'll pop a look once I'm fully awake. My brain hasn't fully ignited yet and this rockstar can't kick in fast enough.

**Comment by Aetherinox** [comment]
Last edits, because I noticed something.

Repo .md pages treat links different. So in the wiki `folder` of the repo, links to other pages need to have `.md` at the end if going to another page
```
PageName.md#HeaderName
```

However, on the actual wiki, links going to other pages are done without the `.md`
```
PageName#HeaderName
```

So you'll have to edit a few **wiki** pages manually. Luckily it's only a few. The actual wiki folder on the repo you added this morning all link fine and require no edit.

---

On Page:
```
https://github.com/acheong08/obi-sync/wiki/Frequently-asked-questions
```

Find Text:
```
Install with Docker-compose
```

Replace Link With:
```
Server-Installation/#docker-compose-option-1
```

`Same page` - Find Text:
```
Install with Docker
```

Replace Link With:
```
Server-Installation#docker-option-2
```

---

On Page:
```
https://github.com/acheong08/obi-sync/wiki/Plugin-Installation
```

Find Text:
```
Creating New User
```

Replace Link With:
```
Server-Installation#creating-new-user
```

---

That should be it, everything else works good. Thanks for the help.

**Comment by acheong08** [comment]
Got it. Editing. Thanks

**Comment by Aetherinox** [comment]
Looks good. I looked around to see how other bigger repos are dealing with multiple people managing repos so it's not a pain for one person, and there is a way, but it's a very hacky way. My brain still isn't running at full speed to even read through the guide right now.

But the wiki should be fine now anyway, other than potential new features and just tweaking the wiki a bit.

Thanks again.
